version: '3.7'

services:
  charge-device-simulator:
    image: charge-device-simulator
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: charge-device-simulator
    volumes:
      - ./config.yaml:/app/config.yaml
      - ../simulator-executor.py:/app/simulator-executor.py
      - ../device/simulator.py:/app/device/simulator.py
    command: [
      "--config=./config.yaml",
      "--simulation=sim1"
    ]
